### ISSUE TITLE
is there a way to use this on an open file?

### ISSUE THREAD

**Issue by vixie** [djherbis/times#12]
that is, similar to the FileInfo Sys() interface, which i can access from f := os.Open(); f.Stat()

**Comment by djherbis** [comment]
Have you considered just using [times.Get](https://godoc.org/github.com/djherbis/times#Get)? That uses FileInfo.Sys() under the hood.

There is a caveat with Windows ChangeTime (only available through times.Stat currently).

**Comment by djherbis** [comment]
I also have [StatFile(file *os.File)](https://pkg.go.dev/github.com/djherbis/times?GOOS=windows#StatFile) on windows only currently, I suppose I could make that method cross platform as well.

**Comment by vixie** [comment]
sorry, missed those. is there documentation apart from the source?

**Comment by djherbis** [comment]
@vixie The links I provided are the documentation [godoc](https://godoc.org/github.com/djherbis/times), there's also the [README](https://github.com/djherbis/times#usage)

What's your use case so I can understand what you're looking for better.

**Comment by vixie** [comment]
ah, ty. the readme doesn't describe Get() and i hadn't noticed the documentation. it's perfect. i use a json file's ctime as the default creation date, in an app here. thanks for doing this.

**Comment by djherbis** [comment]
@vixie Do you rely on ctime on windows? On Windows at least, Get() won't return ctime because Windows requires a file handle for that.

**Comment by vixie** [comment]
no Windows here. i don't have any idea how i'd build or run Golang
software on anything but BSD or Linux. i appreciate the difficulty
and i think your documented design is the right approach. i'm just
not a candidate for it. for me Windows is for gaming.

-- 
Paul Vixie
