### ISSUE TITLE
Use Lstat instead of Stat?

### ISSUE THREAD

**Issue by deitch** [djherbis/times#3]
Any thoughts on using `os.Lstat` instead of `os.Stat`? `Stat` tries to follow symlinks, giving the information about the target, as opposed to the file itself. This means:

* you miss info about the link
* if the target doesn't exist, error

Or maybe have it as an option?

**Comment by djherbis** [comment]
What about using [times.Get](https://godoc.org/github.com/djherbis/times#Get) after [os.Lstat](https://golang.org/pkg/os/#Lstat)?

```go
fi, _ := os.Lstat("myfile")
times.Get(fi)
```

That being said, adding Lstat directly as well sounds like a reasonable ask to me too.

**Comment by deitch** [comment]
Drat. I missed that in the docs. (facepalm)

Thanks @djherbis

**Comment by djherbis** [comment]
One thing to note, times.Get returns only those times that can be obtained by reading the FileInfo object.

times.Stat is allowed to do 'extra work' to fetch more times if possible. 
I've only used this for Windows ctime so far, but if you're looking for that we'd need to add times.Lstat.

**Comment by deitch** [comment]
Ah, it is specifically `ctime` and `atime` that I am looking for.

For now, I am ok with just those 2 and just on linux and darwin, so I build my own 2 files. In doing so, I stumbled across your excellent library.

**Comment by djherbis** [comment]
Yeah ctime should work with Get for linux and darwin, only Windows requires an extra syscall to grab it.

I'll add an Lstat method later to make it the same as Stat.

**Comment by djherbis** [comment]
As a heads up, I added support for times.Lstat a week ago, but I'm waiting on approval to push it.

**Comment by deitch** [comment]
Works like a charm. Thank you!
