### ISSUE TITLE
Return FileFinfo as well as TimeSpec with Stat and LStat functions.

### ISSUE THREAD

**Issue by luckcolors** [djherbis/times#6]
Hello,
I have a usecase where i'm already calling Stat on the files  on wich i have to also get the times for.
Would it be possible to add another set of Stat and LStat wich also return the Fileinfo they used?
Thanks!

I can help with the PR if you think this would be usefull.

**Comment by djherbis** [comment]
Have you considered just using [times.Get](https://godoc.org/github.com/djherbis/times#Get) on the fileinfos you obtained from Stat/Lstat?

The only place that this is functionally different is on Windows, and only for obtaining ChangeTime.

**Comment by luckcolors** [comment]
I did, but that doesn't give me ctime as you said.
If you think it's an overkill, no worries, i'll do the second Stat for getting the timespec. 😄

**Comment by djherbis** [comment]
I don't actually create an os.FileInfo on Windows when we can get change time, it grabs a file handle and calls an extra syscall on it https://github.com/djherbis/times/blob/master/ctime_windows.go.

Do you need cross platform support or only windows? If you have an os.File, I do have times.StatFile on windows which can reuse the file handle from that.

**Comment by luckcolors** [comment]
I would prefer if it was cross platform, at the moment i'm developing this on windows but i would like for it to be working somewhere else too.
At the moment i also don't have a os.File reference because i'm using os.Readdir wich already returns a slice os.Fileinfos.

**Comment by luckcolors** [comment]
Of course i'm not asking to implement an os.Readdir for this lib, but if i had a function like i said previous i could first take the folder listing using File.Readdirnames and then do LStat on every name.

**Comment by djherbis** [comment]
Right, sadly we need a file handle on Windows in order to lookup ChangeTime, and when I lookup ChangeTime this way I don't actually produce an os.FileInfo, so I couldn't return one from times.Stat/Lstat on windows anyway, without doing os.Stat again.

You could make a platform specific split in your code so that non-windows versions could just re-use the os.FileInfo, but sadly on Windows there's no such perf. gain to be had.

**Comment by luckcolors** [comment]
I see, i'm going to that then.
Thanks for the help and information! 😄
